laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Inicio
Route::get('/', 'HomeController@index')->name('index');

// Grupos
Route::get('grupos', 'GroupController@index')->name('groups.index');
Route::get('grupos/{group}/{slug}', 'GroupController@show')->name('groups.show');

// Descargas
Route::get('descargas/{download}/{name}', 'DownloadController@show')->name('downloads.show');

// Textos
Route::get('textos-prestados', 'FileController@index')->name('files.textos-prestados');
Route::get('textos-propios', 'FileController@index')->name('files.textos-propios');
Route::get('traducciones', 'FileController@index')->name('files.traducciones');
Route::get('libros', 'FileController@index')->name('files.libros');
Route::get('textos/{file}/{slug}', 'FileController@show')->name('files.show');

// Contacto
Route::get('contacto', 'ContactoController@index')->name('contacto.index');
Route::post('contacto/enviar', 'ContactoController@send')->name('contacto.enviar');

/**
 * Backend.
 */
Auth::routes(['register' => false, 'reset' => false, 'confirm' => false, 'verify' => false]);
Route::middleware('auth', 'admin')->namespace('Backend')->prefix('admin')->as('admin.')->group(function () {
    // Home
    Route::get('/', 'HomeController@index')->name('home');

    // Grupos
    Route::resource('groups', 'GroupController', ['except' => ['show']]);

    // Archivos
    Route::resource('files', 'FileController', ['except' => ['show']]);
});

// Escritura
Route::resource('escritura', 'EscrituraController');

laravel/resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta name="description" content="Grupos de grupos de grupos">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ $title ?? config('app.name') }}</title>
<script src="{{ asset(mix('js/app.js')) }}" defer></script>
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
<link href="{{ asset(mix('css/app.css')) }}" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/76d4b0a155.js" crossorigin="anonymous" integrity="sha384-WAsFbnLEQcpCk8lM1UTWesAf5rGTCvb2Y+8LvyjAAcxK1c3s5c0L+SYOgxvc6PWG"></script>
<link href="{{ asset(mix('css/main.css')) }}" rel="stylesheet">
@if (app()->environment('production'))
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-62018481-10"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-62018481-10');
    </script>
@endif

laravel/resources/views/includes/main-navbar.blade.php
<nav class="main-navbar navbar navbar-expand-md navbar-light shadow-sm fixed-top">
    <div class="container">
        <a class="navbar-brand {{ Ekko::isActiveRoute('index') }}" href="{{ route('index') }}">
            {{ config('app.name', 'Grupo Martes') }}
        </a>

        <ul class="navbar-nav d-md-none mr-auto ml-2 navbar-current-groups">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actuales</a>
                <div class="dropdown-menu shadow">
                    @foreach ($navGroups as $group)
                        <a class="dropdown-item {{ Ekko::isActive(route('groups.show', [$group, $group->slug], false)) }}" href="{{ route('groups.show', [$group, $group->slug]) }}">
                            {{ $group->title }}
                            @if (auth()->check() && $group->research)
                                <span class="has-research"></span>
                            @endif
                        </a>
                    @endforeach
                </div>
            </li>
        </ul>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Abrir menú">
            <i class="toggler-icon fa fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item {{ Ekko::isActiveRoute('groups.*') }}">
                    <a class="nav-link" href="{{ route('groups.index') }}">Grupos</a>
                </li>
                @guest
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('escritura.index') }}">Lectura</a>
                </li>
                @else
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('escritura.index') }}">Lectura</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('escritura.create') }}">Escritura</a>
                </li>
                @endguest
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('contacto.index') }}">Contacto</a>
                </li>
                <li class="nav-item dropdown ml-md-4 {{ Ekko::isActiveRoute('files.*') }}">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Textos</a>
                    <div class="dropdown-menu shadow">
                        <a class="dropdown-item" href="{{ route('files.textos-prestados') }}">Textos prestados</a>
                        <a class="dropdown-item" href="{{ route('files.textos-propios') }}">Textos propios</a>
                        <a class="dropdown-item" href="{{ route('files.traducciones') }}">Traducciones</a>
                        <a class="dropdown-item" href="{{ route('files.libros') }}">Libros</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                @guest
                    <li class="nav-item">
                        <a class="nav-link nav-link-login" href="{{ route('login') }}">Login</a>
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow">
                            @if (auth()->user()->is_admin)
                                <a class="dropdown-item" href="{{ route('admin.home') }}">Panel</a>
                            @endif
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/includes/scripts.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="{{ asset(mix('/js/plugins.js')) }}"></script>
@stack('scripts')

laravel/resources/views/includes/sidebar.blade.php
<div class="card shadow-sm">
    <div class="card-header">
        <span>Grupos actuales</span>
    </div>
    <div class="list-group list-group-flush">
        @foreach ($navGroups as $group)
            <a class="list-group-item list-group-item-action {{ Ekko::isActive(route('groups.show', [$group, $group->slug], false)) }}" href="{{ route('groups.show', [$group, $group->slug]) }}">
                {{ $group->title }}
                @if (auth()->check() && $group->tasks_count)
                    <span class="has-task"></span>
                @endif
            </a>
        @endforeach
    </div>
</div>